version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: openchat-postgres
    environment:
      POSTGRES_DB: openchat
      POSTGRES_USER: openchat_user
      POSTGRES_PASSWORD: openchat_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U openchat_user -d openchat"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
